name: test_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  http: ^1.2.1
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/

  fonts:
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko/static/Teko-Bold.ttf
        - asset: assets/fonts/Teko/static/Teko-Regular.ttf
          weight: 700



